/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/linkedin': RouteRecordInfo<
      '/linkedin',
      '/linkedin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/medium': RouteRecordInfo<
      '/medium',
      '/medium',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/substack': RouteRecordInfo<
      '/substack',
      '/substack',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/x': RouteRecordInfo<
      '/x',
      '/x',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/linkedin.vue': {
      routes:
        | '/linkedin'
      views:
        | never
    }
    'src/pages/medium.vue': {
      routes:
        | '/medium'
      views:
        | never
    }
    'src/pages/substack.vue': {
      routes:
        | '/substack'
      views:
        | never
    }
    'src/pages/x.vue': {
      routes:
        | '/x'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
